name: Check to Merge
on:
  push:
    branches:
      - "*"
jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm ci
      - run: npx --no-install prettier --check './functions/**/*'
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm ci
      - run: npm test -- --ci
  dry-build:
    name: Dry Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm ci
      - run: npm run build
